name: CI

on:
  push:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker-compose
        run: docker-compose -f ./docker-compose.yml up --build -d

  sast:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      - name: Install Dependencies
        uses: php-actions/composer@v6
        env:
          COMPOSER: "composer.json"
        
      - run: |
          mkdir -p logs/      
    
      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: '.app/'

      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/output.json
          
  dast:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
    
     - name: Build Image for testing
       run: docker-compose -f ./docker-compose.yml up --build -d
 
     - name: ZAP Scan
       uses: zaproxy/action-baseline@v0.6.1
       with:
         target: 'http://localhost:9900'
         cmd_options: '-a -w report_md'    

